version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      # Install dependencies
      - pip install -r docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py